- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
The following configuration's default values have been changed as mentioned:
* table.max.num.tablets --> old: 10, new: 100
* cdc.poll.interval.ms --> old: 200, new: 500
> Changing the default values for polling interval and maximum number of tablets

- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
- debezium-connector-yugabytedb2/src/test/java/io/debezium/connector/yugabytedb/YugabyteDBWrongIncludeListTest.java
If a table is not a part of the stream ID we provide to the DBZ connector configuration, and if it is provided in the `table.include.list` then the connector fails.
The ask is to throw an exception if the above condition is encountered. This PR aims to address the same issue.
There's another flag which is added in this PR i.e. `ignore.exceptions` - the default value for this flag is `false` and if it is set to `true`, the connector will log warnings instead of exceptions.
> Throw exception on wrong table include list

- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
This PR aims to remove the `Thread.sleep()` and use a Debezium's utility class named `Metronome` which provides the `pause()` function to pause the execution for the specified duration.
> Use Metronome utility instead of sleeping

- debezium-connector-yugabytedb2/pom.xml
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/Filters.java
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnectorConfig.java
This PR aims to address the issue where say `db1` and `db2` had the same table named `test` and if the connector was supplied a configuration with the database `db1`, it was throwing an exception for the other `db1` saying that `The table db2.public.test is not a part of the stream id <stream-id>`.
As a part of this PR, the filter is modified to check for the database name also, so that if a table is common in 2 or more databases, we should just pick up the one in the specified database.
Also changed in this PR:
* yb-client version from 0.8.16 to 0.8.17
> Fix to properly filter out tables not a part of the specified database

- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
Earlier, the Debezium Connector for YugabyteDB was going to bootstrap the tablets when the tablets returned a checkpoint `<0,0>` 
That logic has now been changes on the server side, so now if no record has been polled yet for a tablet, the server would send `<-1,-1>` as the checkpoint. This PR aims to appreciate the same on the connector side as well, so now the connector will only go to bootstrap if the checkpoint returned from the server is `<-1,-1>`
> Fix to bootstrap the tablet when it has <-1,-1> as checkpoint

- cdc-server/cdc-server-core/src/main/java/io/debezium/server/DebeziumServer.java
- cdc-server/cdc-server-core/src/main/java/org/yb/MTEngine.java
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBConnector.java
The number of threads is controlled by the property "cdc.threads".
Default is 1
The commit introduces a new engine - MTEngine which is an almost perfect
replica of EmbeddedEngine. The difference is that, MTEngine calls
`connector.taskConfigs` with the right parameter. Similarly it starts a
task with the right task id. EmbeddedEngine has hard coded these values
and is a `public final` class. So it cannot be sub-classed.
Every thread runs an MTEngine which consists of a source and a sink.
Each thread gets the list of tablets and sorts them. Based on the taskId
of each thread, a separate group of tablets is chosen.
Manually tested. Useful log lines:
Number of threads: 4
...
Every task will log the following:
maxTasks = 4
taskId = 1
> Add support for multi-threading in CDC Server.

- debezium-connector-yugabytedb2/pom.xml
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
This PR aims to add a patch which is to log the number of records coming out in a transaction block between the `BEGIN` and `COMMIT` change records. A warning will be logged if the record count is 0.
> Patch to log the number of records in a transactional block

- debezium-connector-yugabytedb2/pom.xml
- debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
This PR aims to make the following amendment:
* Shifting the bootstrap function inside the block for connector retry so that is there's a failure at the bootstrap level, the connector should go for retry.
> Shifting bootstrap function inside retry logic for the connector

- debezium-server/debezium-server-dist/src/main/resources/distro/conf/application.properties.mysql
- debezium-server/debezium-server-dist/src/main/resources/distro/conf/application.properties.oracle
- debezium-server/debezium-server-dist/src/main/resources/distro/conf/application.properties.postgres
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/KafkaConnectRecordParser.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/Record.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/YbExporterConsumer.java
Fixes two bugs:
1. If tombstone events are passed, then the sink plugin was failing to ignore/skip those events.
2. If delete is the first event after debezium restart, it was failing to fetch table metadata.
> Bug fixes in delete events

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/TableSnapshotWriterCSV.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/YbExporterConsumer.java
This PR implements expected behaviour by voyager:
for all source types, it is `<table>_data.sql`
only for non-public schemas in postgres, it is `<schema>.<table>_data.sql`
JIRA: https://yugabyte.atlassian.net/browse/DB-5842
> [DB-5842] Fix: Correct file names for non public postgres tables.

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/ExportStatus.java
- include a serial number for the tables which will enable the implementation of a progress bar for the exporter process
- Atomic write of the export_status.json by writing first to a temp file and then renaming to the correct path
> Export status improvements

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/YbExporterConsumer.java
**Current behaviour**: If there is an unhandled exception in the helper thread, it dies silently(with err in stderr), but main exporter thread continues to run. This is problematic, because the helper thread performs important functions such as keeping exportStatus up-to-date. 
**After this change**: If there is an unhandled exception in the helper thread, the main thread also raises an exception as soon as possible(in the next batch of records received).
> Raise exception in main thread if helper thread dies

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/ExportStatus.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/SequenceObjectUpdater.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/YbExporterConsumer.java
https://yugabyte.atlassian.net/browse/DB-5927
Implementation:
- The config value debezium.sink.ybexporter.column_sequence.map needs to be provided which will have a value of the format  `"<column1>:<sequence1>,<column2>:<sequence2>"`
- A new class SequenceObjectUpdater that keeps track of the max value for each sequence. Each record is processed by this class.
- The ExportStatus has a reference to the map object and keeps updating the value in the json file.
> Capture max of sequences in order to update after migration

- debezium-server/debezium-server-dist/src/main/resources/distro/run.sh
This will enable https://yugabyte.atlassian.net/browse/DB-6092
Example
```
/Users/amakala/Documents/debezium/debezium-server/debezium-server-dist/target/debezium-server/run_dbzm_server.sh dbzmservertest/conf/application.properties
```
basically
1. Pass the properties file as a first argument to the run.sh file. 
2. the run.sh file now can be run from anywhere. It figures out the absolute path and adds the required lib/ .
> Make run.sh runnable from anywhere

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/YbExporterConsumer.java
At the time of snapshot completion, make sure export status is written to disk
> Export status fix

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/ExportStatus.java
Scanned the codebase for presence of any Ints, this was the only incorrect usage.
> Overflow fix: int->long

- .github/workflows/voyager-debezium-workflow.yml
- debezium-server/debezium-server-dist/src/main/resources/distro/run.sh
GH workflow for release automation 
As a result of this automation. the release steps would be:
- create release branch from voyager-main 2.2.0-1.3.0-dev
- create release manually with target = 2.2.0-1.3.0-dev, tag = 2.2.0-1.3.0, prerelease=true
- automation will kick in which should build debezium, and then upload debezium-server as an asset to that release. 
- mark prerelease=false.
> release automation 

- debezium-server/debezium-server-ybexporter/pom.xml
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/TableSnapshotWriterCSV.java
Exporting snapshot in TEXT format because it's easier to parse, and the default format for pg COPY
> TEXT format instead of CSV

- .github/workflows/voyager-debezium-workflow.yml
- Makefile
This modifies the build procedure to include the debezium-server-1.9.5 (from branch `voyager-main-1.9.5` branch) along with the yugabyte connector under dir `debezium-server/debezium-server-fall-forward`.
Overall workflow:
- We maintain two branches (`voyager-main` and `voyager-main-1.9.5`). Every merge has to go to both the branches. 
- On every build of the `voyager-main` it picks up the latest build of the `voyager-main-1.9.5` and includes it in the tar.(along with the yb connector).
During release, we can create separate releases for each, and modify the build workflow to pick up exact builds.
> Workflow for including debezium server 1.9.5 in build

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/EventQueue.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/QueueSegment.java
Scenario: process exits after writing EOF marker of a segment, but before creating next segment file.
on resume, it will try to read the last event json, to get the resume-vsn.
Bug:  Last line is EOF marker, which was causing dbzm to error out.
Fix: Break after EOF marker to get the last event
> fix bug during recovery of vsn if latest segment is full

- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/EventQueue.java
- debezium-server/debezium-server-ybexporter/src/main/java/io/debezium/server/ybexporter/QueueSegment.java
If latest segment is empty while recovering, we have to read the last record in the second latest segment to get the vsn to resume from.
> Fix bug in recovering vsn if latest segment is empty

- Dockerfile
- log4j.properties
Modified Dockerfile to package custom log4j.properties so that the log files can be rolled over when their size exceeds 100MB.
Also changed the Kafka connect JDBC jar being used - this new jar has a custom change to log every sink record going to the target database.
> [DBZ-PGYB] Modified Dockerfile to package custom log4j.properties

- Dockerfile
Changes in this PR:
1. Modification of Dockerfile to include transformers for aiven at the time of docker image compilation
a. Aiven source: https://github.com/Aiven-Open/transforms-for-apache-kafka-connect
> Add aiven transformers to docker build

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/ServerInfo.java
This PR is to add a higher level retry whenever there's a where while starting a PostgresConnectorTask, the failures can include but not limited to the following:
1. Failure of creating JDBC connection
2. Failure to execute query
3. Tserver/master restart
4. Node restart
5. Connection failure
> [DBZ-PGYB] Higher level retry for failures while starting PostgresConnectorTask

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
**Summary**
This PR adds support for the INITIAL_ONLY snapshot mode for Yugabyte.
In the case of Yugabyte also, the snapshot is consumed by executing a snapshot query (SELECT statement) . To ensure that the streaming phase continues exactly from where the snapshot left, this snapshot query is executed as of a specific database state. In YB, this database state is represented by a value of HybridTime. Changes due to transactions with commit_time strictly greater than this snapshot HybridTime will be consumed during the streaming phase.
This value for HybridTime is the value of the "yb_restart_commit_ht" column of the pg_replication_slots view of the associated slot. Thus, in the case of Yugabyte, even for the INITIAL_ONLY snapshot mode, a slot needs to be created if one does not exist. …
> [DBZ-PGYB][#21425] Support for INITIAL_ONLY snapshot mode for Yugabyte

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
Retry in case of failures while task is restarting. Right now any kind of failure will lead to task throwing RetriableException exception causing Task restart.
> Retry in case of failures while task is restarting

- Dockerfile
This PR only changes the link in the `Dockerfile` to fetch the latest custom sink connector jar from GitHub.
According to PR https://github.com/yugabyte/kafka-connect-jdbc/pull/3, changes include the following:
1. Addition of 3 new configuration properties 
* `log.table.balance`:
i. Default is `false` but when set to `true`, the sink connector will execute a query to get the table balance from the target table.
ii. Note that this is only applicable for consistency related tests where the given query is applicable - it will fail if set in any other tests.
* `expected.total.balance`
i. Default is `1000000` (1M) which can be changed to whatever value we are expecting the total balance to be in the target table.
* `tables.for.balance`
i. This takes a comma separated string value for all the …
> [DBZ-PGYB] Get the latest custom JDBC sink image while building docker image

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
PG connector filters out record based on its starting point (WAL position), which in turn depends on the offset received from Kafka. So, in case, the starting point corresponds to a record in the middle of a transaction, PG connector will filter out the records of that transaction with LSN < starting point. 
This creates a problem in the downstream pipeline expects consistency of data. Filtering of records leads to PG connector shipping transaction with missing records. When such a transaction is applied on the sink, consistency breaks.
When 'provide.transaction.metadata' connector configuration is set, PG connector ships transaction boundary records BEGIN/COMMIT. Based on these boundary records, sink connector writes data maintaining consistency. Therefore, when this connector config is …
> Disable records filtering when 'provide.transaction.metadata' config is set

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
Currently the PG debezium connector makes use of smart driver for creating connections to YugabyteDB. The smart driver has in built support for load balancing. However to enable this, the property `load-balance=true` needs to be set in the connection URL.
This PR adds the `load-balance=true` property to the multi host URL used for creating load-balanced connections.
> [DBZ-PGYB] Add load-balance property to multi host url pattern

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
Fixed and trimmed log messages. PG connector skips empty txns and these txns were being logged as a warning with the message "possible data loss", which is not true. Therefore, we are now removing the "possible data loss" log message.
> Fix log statement

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
Based on our testing so far, whenever the PG connector has skipped txns, those txns have always been empty txns.
> Fix log statement wihile skipping empty transactions

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
This PR changes the default plugin in the connector to `yboutput`.
This closes yugabyte/yugabyte-db#23153
> [DBZ-PGYB][yugabyte/yugabyte-db#23153] Change default plugin to yboutput

- debezium-connector-postgres/pom.xml
This PR changes the name of the jar file which gets generated once the connector is compiled. We have changed the name from `debezium-connector-postgres` to `debezium-connector-yugabytedb`.
Additionally, this PR modifies the `name` tag in the `pom.xml` file with the name of the source connector.
> [DBZ-PGYB] Rename jar artefact according to new naming standards

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/pgoutput/PgOutputMessageDecoder.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
Suppose we create a table which has a non-key column which also has a constraint `NOT NULL` - when the connector will start and CDC service will send a `RELATION` message, the column will be marked as "required" since a `NOT NULL` column means that the value should be present.
But for a table with replica identity `CHANGE` the column will not be present in `UPDATE` operations if the column is not updated. This will violate the assumption of the column being marked as "required" since the value will not be present and the connector will end up throwing error of a similar format as:
```
org.apache.kafka.connect.errors.DataException: Invalid value: null used for required field: "name", schema type: STRUCT
```
This PR introduces a fix to the above problem by adding a check while decoding the …
> [DBZ-PGYB] Non-key columns should always be optional for replica identity CHANGE

- pom.xml
The Postgres JDVC driver jar being used currently has a `CRITICAL` vulnerability `CVE-2024-1597` as identified by `trivy` in the version `42.6.0`.
For the fix, this PR upgrades the jar to a driver version `42.6.1` which does not have the vulnerability.
> [DBZ-PGYB] Fix vulnerability in the Postgres JDBC driver

- Dockerfile
This PR fixes the path for the connector jar file to pick up the correct artefact to be packaged in the Docker image.
> [DBZ-PGYB] Dockerfile fix to package proper artefact

- debezium-connector-postgres/YB_DEV_NOTES.md
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/YBRecordsStreamProducerIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/YugabyteReplicaIdentityIT.java
This PR adds the following tests:
1. Streaming for a table with composite PK
2. Streaming with different replica identities with both plugins i.e. `yboutput` and `pgoutput`
3. Streaming changes for a table with foreign key
> [DBZ-PGYB] Add tests to enhance test suite for YugabyteDBConnector

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
This PR adds the logic to throw an exception if a connector is deployed with `decimal.handling.mode=PRECISE`.
> [DBZ-PGYB] Decimal handling mode precise should throw exception

- .github/workflows/yb-release-quay.yml
This PR introduces the following change:
* Version of the pom in the jar file will now be the same as the one being specified in the input form
> [DBZ-PGYB] Modify GitHub Action to publish to set proper versions

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
This PR makes the changes to set the transaction isolation level to `SERIALIZABLE, READ ONLY, DEFERRABLE` before executing the snapshot read query.
> [DBZ-PGYB] Set transaction isolation level before executing snapshot query

- Dockerfile
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
With the current retry model, it was being noticed that the connector ended up retrying infinitely whenever an exception was thrown. This could lead to false positives that the connector is still running while the retries will keep failing.
This PR addresses the issue by adding a check to the task layer so now if the retry count reaches the maximum value, the connector will exit and the task will reach in a failed state - this will help the end user know the status of the task and act accordingly.
This PR also redefines the following properties and changes their default values:
1. `errors.max.retries` - new default value is 60
2. `retriable.restart.connector.wait.ms` - new default value is 30000 (30s)
With the above change, the complete retry duration with the above default configuration …
> [DBZ-PGYB] Restrict retries when retry count reaches limit

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresErrorHandler.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
This PR adds a bug fix which was causing one less number of retries, for example, if `errors.max.retries` was set to 5, the connector was only retrying for 4 times.
Additionally, this PR adds a test to verify the logic.
> [DBZ-PGYB] Bug fix for retry limit and test addition

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/PGCompatible.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/yugabytedb/PGCompatible.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/yugabytedb/SchemaUtil.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/yugabytedb/YBExtractNewRecordState.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/yugabytedb/PGCompatibleTest.java
This PR adds a transformer `PGCompatible` with full path `io.debezium.connector.postgresql.transforms.yugabytedb`, this will be helpful in converting the structure of the emitted events to match the one emitted by standard Debezium connectors.
**Example:**
Consider the following schema for a table `test`: `(id INT PRIMARY KEY, name TEXT, age INT)`
- If a record is inserted having values `(1, 'John Doe', 25)` then after using the above transformer, the `payload` of the record would look like:
```json
"payload": {
"id": 1,
"name": "John Doe",
"age": 25
}
```
- If the same record is now updated and age is changed to 30 i.e. `UPDATE test SET age = 30 WHERE id = 1;` then the `payload` would look like:
```json
"payload": {
"id": 1,
"name": null,
"age": 30
}
```
> **NOTE:** The above example …
> [DBZ-PGYB] Add transformer `PGCompatible` to emit events with standard structure

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
Recent changes in YugabyteDB introduced some changes where the `relcache/catcache` is reloaded as soon as `yb_read_time` is set. Now that caused an issue with the snapshots in the connector i.e. whenever the connector sets the `yb_read_time` and goes on to take the snapshot by running a `SELECT *` query, it gets the following error:
```
Caused by: io.debezium.DebeziumException: com.yugabyte.util.PSQLException: ERROR: The catalog snapshot used for this transaction has been invalidated: expected: 1, got: 0: MISMATCHED_SCHEMA
Where: Catalog Version Mismatch: A DDL occurred while processing this query. Try again.
```
As a workaround, we will now bypass the catalog version check by setting a GUC `yb_disable_catalog_version_check` at the connection level so that we do not hit the error during …
> [DBZ-PGYB][yugabyte/yugabyte-db#25716] Set GUC to disable catalog version check for connections

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/Lsn.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/WalPositionLocator.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
YugabyteDB logical replication now supports creating replication slots with two types of LSN:
1. `SEQUENCE` - This is a monotonic increasing number that will determine the record in global order within the context of a slot. However, this LSN can’t be compared across two LSN’s of different slots.
2. `HYBRID_TIME` - This will mean that the LSN will be denoted by the `HybridTime` of the transaction commit record. All the records of the transaction that is streamed will have the same LSN as that of the commit record. The user has to ensure that the changes of a transaction are applied in totality and the acknowledgement is sent only if the commit record of a transaction is processed. With this mode, the LSN value can be compared across the different slots.
To ensure that the connector also …
> [DBZ-PGYB][yugabyte/yuyabyte-db#24204] Changes to support LSN types with replication slot

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/YugabyteDBConnector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/timescaledb/QueryInformationSchemaMetadata.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/TestHelper.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/connection/PostgresConnectionIT.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/transforms/timescaledb/TimescaleDbDatabaseTest.java
Currently the `load-balance` property in connection URL is hardcoded to true for Multi host pattern. We do not mention any value to this property for single host pattern and as a result it always defaults to false.
This PR makes this property configurable via a connector config. A new connector config `yb.load.balance.connections` has been introduced which determines the value of `load-balance` property in the connection URL. When set to true, the driver fetches and maintains a list of nodes from the given endpoint (even when a single hostname is provided in the config) in the universe and distributes the connections equally across these nodes.
The default value of `yb.load.balance.connections` is true. We may want to set this to false while testing scenarios where we want to have …
> [#26004] Make load-balance property configurable

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresPartition.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTaskContext.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/YugabyteDBConnector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/AbstractYugabyteDBPartitionMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/AbstractYugabyteDBTaskMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBMetricsFactory.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBPartitionMetricsMXBean.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBSnapshotPartitionMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBSnapshotPartitionMetricsMXBean.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBSnapshotTaskMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBStreamingPartitionMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBStreamingPartitionMetricsMXBean.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBStreamingTaskMetrics.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBStreamingTaskMetricsMXBean.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/metrics/YugabyteDBTaskMetricsMXBean.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/snapshot/ParallelSnapshotter.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresPartitionTest.java
- metrics.yml
Currently, the connector follows a single task single partition model and thus uses the `DefaultChangeEventSourceMetricsFactory` which doesn't let us override the metric object names. Since we cannot override names, this causes an issue when we go for the multi task model as there's a conflict in the metric object names if a task registers its metric objects and subsequent tasks try to register their metric objects too.
This is resolved by adding a custom metrics implementation which lets us customise things accordingly for a multi task model. This is done by following the example of metrics implemented by SqlServerConnector at https://github.com/yugabyte/debezium/tree/2.5.2.Final/debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/metrics
This closes …
> [yugabyte/yugabyte-db#26069] Custom metrics implementation for multi task model

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorTask.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresPartition.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/YBValidate.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/YugabyteDBConnector.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/transforms/yugabytedb/Pair.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorConfigDefTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresPartitionTest.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/YBValidateTest.java
This PR introduces the changes to stream changes in parallel using multiple tasks for a table given the user provides the hash_code ranges for it to stream. The following changes have been introduced in this PR:
1. New configurations:
a. `streaming.mode`: This values takes the input as `default` or `parallel` which is then used to decide whether or not parallel streaming mode is supposed to be used.
b. `slot.names`: A list of comma separated values for all the slot names which should be used by each task.
c. `publication.names`: A list of comma separated values for all the publication names which should be used by each task.
d. `slot.ranges`: A list of **semi-colon** separated values for slot ranges in the format `a,b;b,c;c,d`.
2. Validations in the class `YBValidate` have been …
> [yugabyte/yugabyte-db#26107] Parellel streaming changes

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresConnectorConfig.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/YugabyteDBConnector.java
- debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorConfigDefTest.java
This PR fixes the bug while validating the parallel streaming configuration properties and instead of using a common method to validate, we now specify the lambda method directly at the time of `Field` declaration.
> CDC: Fix validation logic for configs related to parallel streaming

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSnapshotChangeEventSource.java
- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
When #172 got merged, we added the logic to begin a read only transaction so that we can use `USE_SNAPSHOT` and capture the snapshot from the same. However, upon transition to streaming, when `PostgresReplicationConnection#startStreaming` during streaming phase, it internally calls `PostgresReplicationConnection#initConnection` and then ``PostgresReplicationConnection#initPublication` which tries to execute an `ALTER` command on the publication.
The `ALTER` command fails owing to the fact that we're still in a read-only transaction opened at the time of slot creation. The exception is similar to:
```
Caused by: org.apache.kafka.connect.errors.ConnectException: Unable to update filtered publication dbz_publication for "public"."test"
at …
```
> [DBZ-PGYB] Bug fix for inability to alter publication upon transitioning to streaming

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java
With the introduction of `slot.lsn.type`, the default value we use for creating the replication slot is `SEQUENCE` when the user does not provide any value to the configuration property. However, while creating the replication slot, if the user doesn't provide this config, the `CREATE_REPLICATION_SLOT` statement looks like:
```
CREATE_REPLICATION_SLOT slot_name LOGICAL plugin_name SEQUENCE;
```
The above breaks the backward compatibility and causes the creation of replication slot to fail on older versions where the newly added syntax is not supported.
As a fix, we will now only specify a LSN type while creating the replication slot if it is `HYBRID_TIME`. For the case with `SEQUENCE`, we will now rely on the default values as specified on the service to create a replication slot of LSN …
> [DBZ-PGYB] Specify only HYBRID_TIME when creating slot, skip otherwise

- debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java
- debezium-connector-postgres/src/test/resources/replication_role_user.ddl
A block of code currently sets the GUC `yb_disable_catalog_version_check` with every connection it creates. The problem here is that if the user is a non-superuser, this block will lead to an error log which doesn't cause any failure but can lead to bad user experience.
Removing the code block from the creation flow of a connection resolves the issue and now:
1. The GUC will not be set when consistent snapshot is disabled by the config `yb.consistent.snapshot=false` or when snapshot is skipped i.e. `snapshot.mode=never`.
2. When using consistent snapshot with a non-superuser, the GUC will only be set when a procedure `disable_catalog_version_check()` is accessible to the connector user.
The procedure can be created by the superuser and be granted to the connector user by executing the …
> [DBZ-PGYB] Do not set GUC to disable catalog version check with every connection

- pom.xml
This PR fixes a reported vulnerability CVE-2024-7254 in the repository by upgrading the dependency version to `3.25.5`.
> fix: upgrade protobuf-jar version to fix reported CVE-2024-7254
